// leave off @2x/@3x
const images = {
	logo: require("../Images/ignitenb.png"),
	logoDark: require("../Images/ignitenbdark.png"),
	clearLogo: require("../Images/top_logo.png"),
	launch: require("../Images/launch-icon.png"),
	ready: require("../Images/your-app.png"),
	ignite: require("../Images/ignite_logo.png"),
	igniteClear: require("../Images/ignite-logo-transparent.png"),
	tileBg: require("../Images/tile_bg.png"),
	background: require("../Images/bg-test.png"),
	//bg: require("../Images/app-bg.png"),
	buttonBackground: require("../Images/button-bg.png"),
	api: require("../Images/Icons/icon-api-testing.png"),
	components: require("../Images/Icons/icon-components.png"),
	deviceInfo: require("../Images/Icons/icon-device-information.png"),
	faq: require("../Images/Icons/faq-icon.png"),
	home: require("../Images/Icons/icon-home.png"),
	theme: require("../Images/Icons/icon-theme.png"),
	usageExamples: require("../Images/Icons/icon-usage-examples.png"),
	chevronRight: require("../Images/Icons/chevron-right.png"),
	hamburger: require("../Images/Icons/hamburger.png"),
	backButton: require("../Images/Icons/back-button.png"),
	closeButton: require("../Images/Icons/close-button.png"),
	initProfileBg: require("../Images/select_image.png"),
	userIcon: require("../Images/user_icon.png"),
	myCare: require("../Images/myCare.png"), 
	cost: require("../Images/cost.png"), 
	diagnostic: require("../Images/diagnostic.png"), 
	prescription: require("../Images/prescription.png"), 
	procedures: require("../Images/procedures.png"), 
	notes: require("../Images/notes.png"), 
};

export default images;
