openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://www.mycare-api/api/v1/
info:
  version: "1.0.0"
  title: MyCare
  description: >-
    This is API spec for MyCare v1.0.0
security:
  - implicit:
      - read
      - write
tags:
  - name: User
    description: user related endpoint
  - name: Blue Button
    description: CMS Blue Button endpoints 
      
paths:
  /user:
    post:
      tags:
        - User
      summary: Create user account -> send confirmation email
      description: >-
        Create user account/send confirmation email
      responses:
        '200':
          description: OK
    get:
      tags:
        - User
      summary: Get user info
      description: >-
        Get user info
      responses:
        '200':
          description: OK
  /user/confirmation:
    post:
      tags:
        - User
      summary:  confirm email (called after email link myapp://email_confirm#...)
      description: >-
        link from email to confirm email address
      security: []
      responses:
        '200':
          description: OK                    
  /user/phone:
    post:
      tags:
        - User
      summary: add phone number (assume one phone) -> send code text message
      description: >-
        Add verification phone number
      security: []
      responses:
        '200':
          description: OK      
  /user/phone/confirmation:
    post:
      tags:
        - User
      summary:  confirm phone number with code (onboarding blocked until verified)
      description: >-
        verify phone number
      security: []
      responses:
        '200':
          description: OK
  /user/sign_in:
    post:
      tags:
        - User
      summary: sign in 
      description: >-
        Sign user in and generate token
      security: []
      responses:
        '200':
          description: OK
  /user/sign_out:
    get:
      tags:
        - User
      summary: sign out
      description: >-
        Sign user out
      security: []
      responses:
        '200':
          description: OK        
  /user/password:
    post:
      tags:
        - User
      summary: Send password reset email to given email
      description: >-
        Enter emails and send password reset email
      security: []
      responses:
        '200':
          description: OK
    put:
      tags:
        - User
      summary: Update password (called after myapp://password_reset#...)
      description: >-
        Update password
      security: []
      responses:
        '200':
          description: OK  
  /user/profile:
    post:
      tags:
        - User
      summary: create or update user profile
      description: >-
        Create or update user profile
      security: []
      responses:
        '200':
          description: OK
    get:
      tags:
        - User
      summary: get user profile
      description: >-
        Get user profile
      security: []
      responses:
        '200':
          description: OK
  /bb/callback:
    get:
      tags:
        - Blue Button
      summary: callback for send token to backend - called after myapp://callback#token=... to store token and start fetching EOB.
      description: >-
        Obtain token and start pulling data
      security: []
      responses:
        '200':
          description: OK  
  /bb/eob:
    get:
      tags:
        - Blue Button
      summary: ping EOB ETL status for blue button. If EOB exists send summary with eob_id
      description: >-
        Get user\'s blue button eob
      security: []
      responses:
        '200':
          description: OK  
  /bb/eob/{eob_id}/entry:
    get:
      tags:
        - Blue Button
      summary: Get list of entries of eob (timeline)
      description: >-
        Get list of entries of eob
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}:
    get:
      tags:
        - Blue Button
      summary: Get entry summary (counts?)
      description: >-
        Get entry summary (counts?)
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/diagnosis:
    get:
      tags:
        - Blue Button
      summary: Get diagnosis list of entry
      description: >-
        Get diagnosis list of entry
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/diagnosis/{diagnosis_id}:
    get:
      tags:
        - Blue Button
      summary: Get diagnosis detail
      description: >-
        Get diagnosis detail
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/procedure:
    get:
      tags:
        - Blue Button
      summary: Get procedure list of entry
      description: >-
        Get procedure list of entry
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/procedure/{procedure_id}:
    get:
      tags:
        - Blue Button
      summary: Get procedure details
      description: >-
        Get procedure details
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/cost:
    get:
      tags:
        - Blue Button
      summary: Get payment summary
      description: >-
        Get payment summary
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/prescription:
    get:
      tags:
        - Blue Button
      summary: Get prescription list
      description: >-
        Get prescription list
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/prescription/{prescription_id}:
    get:
      tags:
        - Blue Button
      summary: Get prescription details
      description: >-
        Get prescription detail
      security: []
      responses:
        '200':
          description: OK
  /bb/eob/{eob_id}/entry/{entry_id}/note:
    get:
      tags:
        - Blue Button
      summary: Get notes
      description: >-
        Get notes
      security: []
      responses:
        '200':
          description: OK

components:
  schemas: {}
  securitySchemes:
    implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/oauth/auth'
          scopes:
            write: allows modifying resources
            read: allows reading resources
