openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://www.mycare-api/api/v1/
info:
  version: "1.0.0"
  title: MyCare
  description: >-
    This is API spec for MyCare v1.0.0
security:
  - implicit:
      - read
      - write
tags:
  - name: User
    description: user related endpoint
  - name: Payer
    description: Payer endpoints 
  - name: Patient
    description: Patient endpoints 
  - name: Provider
    description: Provider endpoints
    
paths:
  /user:
    post:
      tags:
        - User
      summary: Create user account -> send confirmation email
      description: >-
        Create user account/send confirmation email
      responses:
        '200':
          description: OK
    get:
      tags:
        - User
      summary: Get user info
      description: >-
        Get user info
      responses:
        '200':
          description: OK
  /user/confirmation:
    post:
      tags:
        - User
      summary:  confirm email (called after email link myapp://email_confirm#...)
      description: >-
        link from email to confirm email address
      security: []
      responses:
        '200':
          description: OK                    
  /user/phone:
    post:
      tags:
        - User
      summary: add phone number (assume one phone) -> send code text message
      description: >-
        Add verification phone number
      security: []
      responses:
        '200':
          description: OK      
  /user/phone/confirmation:
    post:
      tags:
        - User
      summary:  confirm phone number with code (onboarding blocked until verified)
      description: >-
        verify phone number
      security: []
      responses:
        '200':
          description: OK
  /user/sign_in:
    post:
      tags:
        - User
      summary: sign in 
      description: >-
        Sign user in and generate token
      security: []
      responses:
        '200':
          description: OK
  /user/sign_out:
    get:
      tags:
        - User
      summary: sign out
      description: >-
        Sign user out
      security: []
      responses:
        '200':
          description: OK        
  /user/password:
    post:
      tags:
        - User
      summary: Send password reset email to given email
      description: >-
        Enter emails and send password reset email
      security: []
      responses:
        '200':
          description: OK
    put:
      tags:
        - User
      summary: Update password (called after myapp://password_reset#...)
      description: >-
        Update password
      security: []
      responses:
        '200':
          description: OK  
  /user/profile:
    put:
      tags:
        - User
      summary: update user profile
      description: >-
        update user profile
      security: []
      responses:
        '200':
          description: OK
    get:
      tags:
        - User
      summary: get user profile
      description: >-
        Get user profile
      security: []
      responses:
        '200':
          description: OK
  /payer:
    post:
      tags:
        - Payer
      summary: Create payer
      description: >-
        Get all available payers
      security: []
      responses:
        '200':
          description: OK  
    get:
      tags:
        - Payer
      summary: Get all integrated payers
      description: >-
        Get all available payers
      security: []
      responses:
        '200':
          description: OK  
  /payer/{payer_id}/code:
    get:
      tags:
        - Payer
      summary: callback for send code to backend - called after myapp://callback#code=... to store code and start fetching EOB.
      description: >-
        Obtain code and start pulling data
      security: []
      responses:
        '200':
          description: OK  
  /payer/{payer_id}/eob:
    get:
      tags:
        - Payer
      summary: get eobs from payer
      description: >-
        Get user\'s payer eob
      security: []
      responses:
        '200':
          description: OK  
  /payer/{payer_id}/eob/status:
    get:
      tags:
        - Payer
      summary: ping EOB ETL status for payer. If EOB exists send summary with eob_id
      description: >-
        Get user\'s payer eob
      security: []
      responses:
        '200':
          description: OK  
  /payer/{payer_id}/eob/{eob_id}/provider:
    get:
      tags:
        - Payer
      summary: Get list of unique providers in eob
      description: >-
        Get list of entries of eob
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/provider/{provider_id}:
    get:
      tags:
        - Payer
      summary: Get provider infomation
      description: >-
        Get list of entries of eob
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/provider/{provider_id}/code:
    get:      
      tags:
        - Payer
      summary: provider callback after OAuth
      description: >-
        Get list of entries of eob
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/provider/{provider_id}/consent:
    post:
      tags:
        - Payer
      summary: Get list of providers within organization
      description: >-
        Get list of entries of eob
      security: []
      responses:
        '200':
          description: OK  
  /payer/{payer_id}/eob/{eob_id}/entry:
    get:
      tags:
        - Payer
      summary: Get list of entries of eob (timeline)
      description: >-
        Get list of entries of eob
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/entry/{entry_id}:
    get:
      tags:
        - Payer
      summary: Get entry summary (counts?)
      description: >-
        Get entry summary (counts?)
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/entry/{entry_id}/diagnosis:
    get:
      tags:
        - Payer
      summary: Get diagnosis list of entry
      description: >-
        Get diagnosis list of entry
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/entry/{entry_id}/procedure:
    get:
      tags:
        - Payer
      summary: Get procedure list of entry
      description: >-
        Get procedure list of entry
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/entry/{entry_id}/cost:
    get:
      tags:
        - Payer
      summary: Get payment summary
      description: >-
        Get payment summary
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/entry/{entry_id}/prescription:
    get:
      tags:
        - Payer
      summary: Get prescription list
      description: >-
        Get prescription list
      security: []
      responses:
        '200':
          description: OK
  /payer/{payer_id}/eob/{eob_id}/entry/{entry_id}/note:
    get:
      tags:
        - Payer
      summary: Get notes
      description: >-
        Get notes
      security: []
      responses:
        '200':
          description: OK
  /patient/timeline:
    get:
      tags:
        - Patient
      summary: Get aggregated EOB timeline 
      description: >-
        Get aggregated EOB timeline 
      security: []
      responses:
        '200':
          description: OK
  /patient/share:
    get:
      tags:
        - Patient
      summary: Show shared providers
      description: >-
        Show shared providers
      security: []
      responses:
        '200':
          description: OK
    post:
      tags:
        - Patient
      summary: Share data with provider
      description: >-
        Share data with provider
      security: []
      responses:
        '200':
          description: OK
  /provider/patient:
    get:
      tags:
        - Provider
      summary: Show list of patients who agreed to share
      description: >-
        Show list of patients who agreed to share
      security: []
      responses:
        '200':
          description: OK
  /provider/search:
    get:
      tags:
        - Provider
      summary: Search provider list
      description: >-
        Search provider list
      security: []
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes:
    implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/oauth/auth'
          scopes:
            write: allows modifying resources
            read: allows reading resources
